version = 0.1
[default.deploy.parameters]
stack_name = "news-subscribe-aws"
resolve_s3 = true
s3_prefix = "news-subscribe-aws"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "S3BucketName=\"news-audio-files-kenchang198-dev\""
image_repositories = []
