AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: News Subscribe App - Lambda Function

Globals:
  Function:
    Timeout: 600
    MemorySize: 512

Conditions:
  CreateNewBucket: !Equals [!Ref CreateS3Bucket, "true"]
  HasBucketName: !Not [!Equals [!Ref S3BucketName, ""]]
  UseProvidedBucket: !And [!Condition HasBucketName, !Not [!Condition CreateNewBucket]]

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Condition: CreateNewBucket
    Properties:
      BucketName: !If
        - HasBucketName
        - !Ref S3BucketName
        - !Sub "news-audio-files-${AWS::AccountId}-${Environment}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
  NewsProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "news-processing-${Environment}"
      CodeUri: ./
      # Handler: src/main.lambda_handler
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Architectures:
        - x86_64
      Environment:
        Variables:
          S3_BUCKET_NAME: !If
            - CreateNewBucket
            - !Ref S3Bucket
            - !If
              - HasBucketName
              - !Ref S3BucketName
              - !Sub "news-audio-files-${AWS::AccountId}-${Environment}"
          S3_PREFIX: !Ref S3Prefix
          OPENAI_API_KEY: !Ref OpenAIApiKey
          GOOGLE_API_KEY: !Ref GoogleApiKey
          AI_PROVIDER: !Ref AIProvider
          GEMINI_MODEL: !Ref GeminiModel
          OPENAI_MODEL: !Ref OpenAIModel
          POLLY_VOICE_ID: !Ref PollyVoiceId
          SUMMARY_MAX_LENGTH: !Ref SummaryMaxLength
          PROGRAM_NAME: !Ref ProgramName
          TZ: !Ref TimeZone
          ENVIRONMENT: !Ref Environment
      Policies:
        - AmazonPollyFullAccess
        - S3FullAccessPolicy:
            BucketName: !If
              - CreateNewBucket
              - !Ref S3Bucket
              - !If
                - HasBucketName
                - !Ref S3BucketName
                - !Sub "news-audio-files-${AWS::AccountId}-${Environment}"
      Events:
        ScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: cron(0 22 ? * * *)
            Name: !Sub "NewsProcessingSchedule-${Environment}"
            Description: !Sub "Triggers the news processing function every day at 7 AM JST (${Environment})"

Parameters:
  Environment:
    Type: String
    Default: stg
    AllowedValues:
      - stg
      - prod
    Description: Environment name (stg or prod)

  S3BucketName:
    Type: String
    Default: ""
    Description: Name of the S3 bucket for storing audio files (leave empty to auto-generate)
  
  CreateS3Bucket:
    Type: String
    Default: "true"
    AllowedValues:
      - "true"
      - "false"
    Description: Whether to create a new S3 bucket

  S3Prefix:
    Type: String
    Default: audio/
    Description: S3 prefix for storing audio files

  OpenAIApiKey:
    Type: String
    NoEcho: true
    Description: OpenAI API Key (Legacy Support)

  GoogleApiKey:
    Type: String
    NoEcho: true
    Description: Google Gemini API Key

  AIProvider:
    Type: String
    Default: gemini
    Description: AI Provider (openai or gemini)

  GeminiModel:
    Type: String
    Default: gemini-1.5-pro
    Description: Gemini Model Name

  OpenAIModel:
    Type: String
    Default: gpt-3.5-turbo
    Description: OpenAI Model Name

  PollyVoiceId:
    Type: String
    Default: Takumi
    Description: Amazon Polly Voice ID for Japanese speech synthesis

  SummaryMaxLength:
    Type: String
    Default: "400"
    Description: Maximum length for article summaries

  TimeZone:
    Type: String
    Default: Asia/Tokyo
    Description: Linux TZ database name for the Lambda runtime (e.g., Asia/Tokyo)

  ProgramName:
    Type: String
    Default: Tech News Radio
    Description: Name of the news program

Outputs:
  NewsProcessingFunction:
    Description: News Processing Lambda Function ARN
    Value: !GetAtt NewsProcessingFunction.Arn

  NewsProcessingFunctionName:
    Description: News Processing Lambda Function Name
    Value: !Ref NewsProcessingFunction

  S3BucketName:
    Description: S3 bucket for audio files
    Value: !If
      - CreateNewBucket
      - !Ref S3Bucket
      - !If
        - HasBucketName
        - !Ref S3BucketName
        - !Sub "news-audio-files-${AWS::AccountId}-${Environment}"

  Environment:
    Description: Deployment environment
    Value: !Ref Environment
